covid_19:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: '{{ env_var("SQL_DRIVER") }}'
      server: '{{ env_var("SQL_SERVER") }}'
      port: '{{ env_var("SQL_PORT") | int }}'
      database: '{{ env_var("SQL_DB") }}'
      schema: dbo
      user: '{{ env_var("SQL_USER") }}'
      password: '{{ env_var("SQL_PASSWORD") }}'
      trust_cert: True